/*
 *    Copyright 2009-2023 the original author or authors.
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *       https://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */
package pro.chenggang.project.reactive.mybatis.support.r2dbc.spring.application.mapper;

import org.apache.ibatis.annotations.Mapper;
import pro.chenggang.project.reactive.mybatis.support.r2dbc.spring.application.entity.extend.DeptWithEmp;
import pro.chenggang.project.reactive.mybatis.support.r2dbc.spring.application.entity.model.Dept;
import pro.chenggang.project.reactive.mybatis.support.r2dbc.spring.application.mapper.dynamic.DeptDynamicMapper;
import pro.chenggang.project.reactive.mybatis.support.r2dbc.spring.application.mapper.dynamic.DeptDynamicSqlSupport;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;

import java.time.LocalDateTime;

import static org.mybatis.dynamic.sql.SqlBuilder.isEqualTo;

/**
 * auto generated
 * @author AutoGenerated
 */
@Mapper
public interface DeptMapper extends DeptDynamicMapper {

    default Mono<Long> count(){
        return count(dsl -> dsl);
    }

    default Flux<Dept> selectAll(){
        return select(dsl -> dsl);
    }

    default Mono<Dept> selectOneByDeptNo(Long deptNo){
        return selectOne(dsl -> dsl
                .where(DeptDynamicSqlSupport.deptNo,isEqualTo(deptNo))
        );
    }

    default Flux<Dept> selectListByTime(LocalDateTime createTime){
        return select(dsl -> dsl
                .where(DeptDynamicSqlSupport.createTime,isEqualTo(createTime))
        );
    }

    default Mono<Integer> deleteByDeptNo(Long deptNo){
        return delete(dsl -> dsl
                .where(DeptDynamicSqlSupport.deptNo,isEqualTo(deptNo))
        );
    }

    default Mono<Integer> updateByDeptNo(Dept dept){
        return updateAllByPrimaryKey(dept);
    }

    Flux<DeptWithEmp> selectDeptWithEmpList();
}