package pro.chenggang.project.reactive.mybatis.support.r2dbc.spring.application.mapper;

import org.apache.ibatis.annotations.Mapper;
import pro.chenggang.project.reactive.mybatis.support.r2dbc.spring.application.entity.extend.EmpWithDept;
import pro.chenggang.project.reactive.mybatis.support.r2dbc.spring.application.mapper.dynamic.EmpDynamicMapper;
import reactor.core.publisher.Flux;

/**
 * auto generated
 * @author AutoGenerated
 */
@Mapper
public interface EmpMapper extends EmpDynamicMapper {

    Flux<EmpWithDept> selectEmpWithDeptList();
}