package pro.chenggang.project.reactive.mybatis.support.r2dbc.spring.application.mapper;

import org.apache.ibatis.annotations.Mapper;
import pro.chenggang.project.reactive.mybatis.support.r2dbc.spring.application.mapper.dynamic.PeopleDynamicMapper;

/**
 * auto generated
 * @author AutoGenerated
 */
@Mapper
public interface PeopleMapper extends PeopleDynamicMapper {
}