/*
 *    Copyright 2009-2024 the original author or authors.
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *       https://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */
package pro.chenggang.project.reactive.mybatis.support.r2dbc.spring.common.entity;

import lombok.AllArgsConstructor;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

import java.time.LocalDateTime;

/**
 * dept
 * 
 * @author AutoGenerated
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode
@ToString
public class Dept {
    /**
     * dept no
     */
    protected Long deptNo;

    /**
     * dept name
     */
    protected String deptName;

    /**
     * location
     */
    protected String location;

    /**
     * create time
     */
    protected LocalDateTime createTime;

    public static final String DEPT_NO = "deptNo";

    public static final String DB_DEPT_NO = "dept_no";

    public static final String DEPT_NAME = "deptName";

    public static final String DB_DEPT_NAME = "dept_name";

    public static final String LOCATION = "location";

    public static final String DB_LOCATION = "location";

    public static final String CREATE_TIME = "createTime";

    public static final String DB_CREATE_TIME = "create_time";
}