/*
 *    Copyright 2009-2023 the original author or authors.
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *       https://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */
package pro.chenggang.project.reactive.mybatis.support.r2dbc.spring.common.entity;

import lombok.AllArgsConstructor;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * emp
 * 
 * @author AutoGenerated
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode
@ToString
public class Emp {
    /**
     * emp no
     */
    protected Long empNo;

    /**
     * emp name
     */
    protected String empName;

    /**
     * job
     */
    protected String job;

    /**
     * manager
     */
    protected String manager;

    /**
     * hire date
     */
    protected LocalDate hireDate;

    /**
     * salary
     */
    protected Integer salary;

    /**
     * kpi
     */
    protected BigDecimal kpi;

    /**
     * dept no
     */
    protected Long deptNo;

    /**
     * create time
     */
    protected LocalDateTime createTime;

    public static final String EMP_NO = "empNo";

    public static final String DB_EMP_NO = "emp_no";

    public static final String EMP_NAME = "empName";

    public static final String DB_EMP_NAME = "emp_name";

    public static final String JOB = "job";

    public static final String DB_JOB = "job";

    public static final String MANAGER = "manager";

    public static final String DB_MANAGER = "manager";

    public static final String HIRE_DATE = "hireDate";

    public static final String DB_HIRE_DATE = "hire_date";

    public static final String SALARY = "salary";

    public static final String DB_SALARY = "salary";

    public static final String KPI = "kpi";

    public static final String DB_KPI = "kpi";

    public static final String DEPT_NO = "deptNo";

    public static final String DB_DEPT_NO = "dept_no";

    public static final String CREATE_TIME = "createTime";

    public static final String DB_CREATE_TIME = "create_time";
}