package pro.chenggang.project.reactive.mybatis.support.r2dbc.application.entity.model;

import lombok.*;
import lombok.experimental.Accessors;

import java.time.LocalDateTime;

/**
 * auto generated
 * @author AutoGenerated
 */
@ToString
@Getter
@Setter
@Accessors(chain = true)
@NoArgsConstructor
@AllArgsConstructor
@Builder
@EqualsAndHashCode
public class Dept {
    /**
     * dept no
     */
    protected Long deptNo;

    /**
     * dept name
     */
    protected String deptName;

    /**
     * location
     */
    protected String location;

    /**
     * create time
     */
    protected LocalDateTime createTime;

    public static final String DEPT_NO = "deptNo";

    public static final String DB_DEPT_NO = "dept_no";

    public static final String DEPT_NAME = "deptName";

    public static final String DB_DEPT_NAME = "dept_name";

    public static final String LOCATION = "location";

    public static final String DB_LOCATION = "location";

    public static final String CREATE_TIME = "createTime";

    public static final String DB_CREATE_TIME = "create_time";
}