package pro.chenggang.project.reactive.mybatis.support.r2dbc.application.entity.model;

import lombok.*;
import lombok.experimental.Accessors;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * auto generated
 * @author AutoGenerated
 */
@ToString
@Getter
@Setter
@Accessors(chain = true)
@NoArgsConstructor
@AllArgsConstructor
@Builder
@EqualsAndHashCode
public class Emp {
    /**
     * emp no
     */
    protected Long empNo;

    /**
     * emp name
     */
    protected String empName;

    /**
     * job
     */
    protected String job;

    /**
     * manager
     */
    protected String manager;

    /**
     * hire date
     */
    protected LocalDate hireDate;

    /**
     * salary
     */
    protected Integer salary;

    /**
     * kpi
     */
    protected BigDecimal kpi;

    /**
     * dept no
     */
    protected Long deptNo;

    /**
     * create time
     */
    protected LocalDateTime createTime;

    public static final String EMP_NO = "empNo";

    public static final String DB_EMP_NO = "emp_no";

    public static final String EMP_NAME = "empName";

    public static final String DB_EMP_NAME = "emp_name";

    public static final String JOB = "job";

    public static final String DB_JOB = "job";

    public static final String MANAGER = "manager";

    public static final String DB_MANAGER = "manager";

    public static final String HIRE_DATE = "hireDate";

    public static final String DB_HIRE_DATE = "hire_date";

    public static final String SALARY = "salary";

    public static final String DB_SALARY = "salary";

    public static final String KPI = "kpi";

    public static final String DB_KPI = "kpi";

    public static final String DEPT_NO = "deptNo";

    public static final String DB_DEPT_NO = "dept_no";

    public static final String CREATE_TIME = "createTime";

    public static final String DB_CREATE_TIME = "create_time";
}