package pro.chenggang.project.reactive.mybatis.support.common.entity;

import lombok.AllArgsConstructor;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

import java.time.LocalDate;

/**
 * auto generated
 * 
 * @author AutoGenerated
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode
@ToString
public class Project {
    /**
     * project no
     */
    protected Long projectId;

    /**
     * emp no
     */
    protected Long empNo;

    /**
     * start date
     */
    protected LocalDate startDate;

    /**
     * end date
     */
    protected LocalDate endDate;

    public static final String PROJECT_ID = "projectId";

    public static final String DB_PROJECT_ID = "project_id";

    public static final String EMP_NO = "empNo";

    public static final String DB_EMP_NO = "emp_no";

    public static final String START_DATE = "startDate";

    public static final String DB_START_DATE = "start_date";

    public static final String END_DATE = "endDate";

    public static final String DB_END_DATE = "end_date";
}