/*
 *    Copyright 2009-2023 the original author or authors.
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *       https://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */
package pro.chenggang.project.reactive.mybatis.support.common.entity;

import lombok.AllArgsConstructor;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * auto generated
 * 
 * @author AutoGenerated
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode
@ToString
public class SubjectData {
    protected Byte abyte;

    protected Short ashort;

    protected String achar;

    protected Integer anint;

    protected Long along;

    protected Float afloat;

    protected Double adouble;

    protected Boolean aboolean;

    protected String astring;

    protected SubjectDataAEnum anenum;

    protected BigDecimal adecimal;

    protected Timestamp atimestamp;

    protected LocalDate adate;

    protected LocalDateTime adatetime;

    public static final String ABYTE = "abyte";

    public static final String DB_ABYTE = "aByte";

    public static final String ASHORT = "ashort";

    public static final String DB_ASHORT = "aShort";

    public static final String ACHAR = "achar";

    public static final String DB_ACHAR = "aChar";

    public static final String ANINT = "anint";

    public static final String DB_ANINT = "anInt";

    public static final String ALONG = "along";

    public static final String DB_ALONG = "aLong";

    public static final String AFLOAT = "afloat";

    public static final String DB_AFLOAT = "aFloat";

    public static final String ADOUBLE = "adouble";

    public static final String DB_ADOUBLE = "aDouble";

    public static final String ABOOLEAN = "aboolean";

    public static final String DB_ABOOLEAN = "aBoolean";

    public static final String ASTRING = "astring";

    public static final String DB_ASTRING = "aString";

    public static final String ANENUM = "anenum";

    public static final String DB_ANENUM = "anEnum";

    public static final String ADECIMAL = "adecimal";

    public static final String DB_ADECIMAL = "aDecimal";

    public static final String ATIMESTAMP = "atimestamp";

    public static final String DB_ATIMESTAMP = "aTimestamp";

    public static final String ADATE = "adate";

    public static final String DB_ADATE = "aDate";

    public static final String ADATETIME = "adatetime";

    public static final String DB_ADATETIME = "aDateTime";
}