package pro.chenggang.project.reactive.mybatis.support.generator.mapper;

import org.apache.ibatis.annotations.Mapper;
import pro.chenggang.project.reactive.mybatis.support.generator.mapper.dynamic.DeptDynamicMapper;

/**
 * auto generated
 * @author AutoGenerated
 */
@Mapper
public interface DeptMapper extends DeptDynamicMapper {
}