package pro.chenggang.project.reactive.mybatis.support.r2dbc.application.mapper;

import org.apache.ibatis.annotations.Mapper;

/**
 * auto generated
 * @author AutoGenerated
 */
@Mapper
public interface BrandMapper {
}