package pro.chenggang.project.reactive.mybatis.support.r2dbc.application.mapper;

import org.apache.ibatis.annotations.Mapper;
import pro.chenggang.project.reactive.mybatis.support.r2dbc.application.entity.model.Dept;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;

import java.time.LocalDateTime;

/**
 * auto generated
 * @author AutoGenerated
 */
@Mapper
public interface DeptMapper {

    Flux<Dept> selectAll();

    Mono<Dept> selectOneByDeptNo(Long deptNo);

    Flux<Dept> selectListByTime(LocalDateTime createTime);
}