package pro.chenggang.project.reactive.mybatis.support.r2dbc.application.mapper;

import org.apache.ibatis.annotations.Mapper;
import pro.chenggang.project.reactive.mybatis.support.r2dbc.application.entity.extend.EmpWithDept;
import reactor.core.publisher.Flux;

/**
 * auto generated
 * @author AutoGenerated
 */
@Mapper
public interface EmpMapper {

    Flux<EmpWithDept> selectEmpWithDeptList();
}