package pro.chenggang.project.reactive.mybatis.support.r2dbc.application.mapper;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import pro.chenggang.project.reactive.mybatis.support.r2dbc.application.model.People;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;

import java.util.List;
import java.util.Map;

/**
 * auto generated
 * @author AutoGenerated
 */
@Mapper
public interface PeopleMapper {

    Mono<Integer> batchInsert(@Param("peopleList") List<People> peopleList);

    Mono<Integer> insert(People People);

    Mono<Boolean> update(People demo);

    Mono<People> findById(Integer id);

    Mono<People> dynamicFindExample(People example);

    Mono<Map<String, Object>> find2ById(Integer id);

    @Select("SELECT id, nick, created_at FROM people WHERE nick = #{nick}")
    @ResultMap("PeopleResultMap")
    Mono<People> findByNick(@Param("nick") String nick);

    Flux<People> findAll();

    Mono<Long> getAllCount();
}