package pro.chenggang.project.reactive.mybatis.support.r2dbc.application.mapper;

import org.apache.ibatis.annotations.Mapper;
import pro.chenggang.project.reactive.mybatis.support.r2dbc.application.model.StoreWithBrand;
import reactor.core.publisher.Flux;

/**
 * auto generated
 * @author AutoGenerated
 */
@Mapper
public interface StoreMapper {

    Flux<StoreWithBrand> selectAllStoreWithUser();
}