package pro.chenggang.project.reactive.mybatis.support.r2dbc.application.mapper;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import pro.chenggang.project.reactive.mybatis.support.r2dbc.application.model.UserWithStore;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;

/**
 * auto generated
 * @author AutoGenerated
 */
@Mapper
public interface UserMapper {

    /**
     * select users by accountId
     * @param accountId
     * @return
     */
    Flux<UserWithStore> selectUsersByAccountId(@Param("accountId") String accountId);

    /**
     * select user by accountI and storeId
     * @param accountId
     * @param storeId
     * @return
     */
    Mono<UserWithStore> selectUserByAccountIdAndStoreId(@Param("accountId") String accountId, @Param("storeId") String storeId);


}