package pro.chenggang.project.reactive.mybatis.support.r2dbc.spring.application.entity.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;

import java.time.LocalDateTime;

/**
 * auto generated
 * @author AutoGenerated
 */
@ToString
@Getter
@Setter
@Accessors(chain = true)
@NoArgsConstructor
@AllArgsConstructor
@Builder
@EqualsAndHashCode
public class People {
    /**
     * auto_increment_id
     */
    protected Integer id;

    /**
     * nickname
     */
    protected String nick;

    /**
     * create_time
     */
    protected LocalDateTime createdAt;

    public static final String ID = "id";

    public static final String DB_ID = "id";

    public static final String NICK = "nick";

    public static final String DB_NICK = "nick";

    public static final String CREATED_AT = "createdAt";

    public static final String DB_CREATED_AT = "created_at";
}