package pro.chenggang.project.reactive.mybatis.support.generator.mapper;

import org.apache.ibatis.annotations.Mapper;
import pro.chenggang.project.reactive.mybatis.support.generator.mapper.dynamic.EmpDynamicMapper;

/**
 * auto generated
 * @author AutoGenerated
 */
@Mapper
public interface EmpMapper extends EmpDynamicMapper {
}