package pro.chenggang.project.reactive.mybatis.support.r2dbc.application.model;

import lombok.*;
import lombok.experimental.Accessors;

import java.time.LocalDateTime;

/**
 * auto generated
 * @author AutoGenerated
 */
@ToString
@Getter
@Setter
@Accessors(chain = true)
@NoArgsConstructor
@AllArgsConstructor
@Builder
@EqualsAndHashCode
public class Brand {
    /**
     * 自增ID
     */
    protected Long id;

    /**
     * 品牌ID
     */
    protected String uid;

    /**
     * 品牌名称
     */
    protected String brandName;

    /**
     * 品牌Nick
     */
    protected String brandNick;

    /**
     * 是否启用，1是，2否
     */
    protected Integer enableFlag;

    /**
     * 是否删除，1是，2否
     */
    protected Integer deleteFlag;

    /**
     * 创建时间
     */
    protected LocalDateTime createTime;

    /**
     * 创建人
     */
    protected String createUser;

    /**
     * 修改时间
     */
    protected LocalDateTime updateTime;

    /**
     * 更新人
     */
    protected String updateUser;

    public static final String ID = "id";

    public static final String DB_ID = "id";

    public static final String UID = "uid";

    public static final String DB_UID = "uid";

    public static final String BRAND_NAME = "brandName";

    public static final String DB_BRAND_NAME = "brand_name";

    public static final String BRAND_NICK = "brandNick";

    public static final String DB_BRAND_NICK = "brand_nick";

    public static final String ENABLE_FLAG = "enableFlag";

    public static final String DB_ENABLE_FLAG = "enable_flag";

    public static final String DELETE_FLAG = "deleteFlag";

    public static final String DB_DELETE_FLAG = "delete_flag";

    public static final String CREATE_TIME = "createTime";

    public static final String DB_CREATE_TIME = "create_time";

    public static final String CREATE_USER = "createUser";

    public static final String DB_CREATE_USER = "create_user";

    public static final String UPDATE_TIME = "updateTime";

    public static final String DB_UPDATE_TIME = "update_time";

    public static final String UPDATE_USER = "updateUser";

    public static final String DB_UPDATE_USER = "update_user";
}