package pro.chenggang.project.reactive.mybatis.support.r2dbc.application.model;

import lombok.*;
import lombok.experimental.Accessors;

import java.time.LocalDateTime;

/**
 * auto generated
 * @author AutoGenerated
 */
@ToString
@Getter
@Setter
@Accessors(chain = true)
@NoArgsConstructor
@AllArgsConstructor
@Builder
@EqualsAndHashCode
public class Store {
    /**
     * 自增ID
     */
    protected Long id;

    /**
     * 门店ID
     */
    protected String uid;

    /**
     * 品牌ID
     */
    protected String brandId;

    /**
     * 门店名称
     */
    protected String storeName;

    /**
     * 门店Nick
     */
    protected String storeNick;

    /**
     * 省
     */
    protected String province;

    /**
     * 市
     */
    protected String city;

    /**
     * 区
     */
    protected String district;

    /**
     * 所属大区
     */
    protected String region;

    /**
     * 地址
     */
    protected String address;

    /**
     * 联系人
     */
    protected String contact;

    /**
     * 联系人电话
     */
    protected String contactTel;

    /**
     * 联系人职务
     */
    protected String contactJob;

    /**
     * IT联系人
     */
    protected String itContact;

    /**
     * IT联系人电话
     */
    protected String itContactTel;

    /**
     * 短信签名
     */
    protected String smsSign;

    /**
     * 是否初始化，1是，2否
     */
    protected Integer initFlag;

    /**
     * 是否启用，1是，2否
     */
    protected Integer enableFlag;

    /**
     * 是否删除，1是，2否
     */
    protected Integer deleteFlag;

    /**
     * 创建时间
     */
    protected LocalDateTime createTime;

    /**
     * 创建人
     */
    protected String createUser;

    /**
     * 修改时间
     */
    protected LocalDateTime updateTime;

    /**
     * 更新人
     */
    protected String updateUser;

    public static final String ID = "id";

    public static final String DB_ID = "id";

    public static final String UID = "uid";

    public static final String DB_UID = "uid";

    public static final String BRAND_ID = "brandId";

    public static final String DB_BRAND_ID = "brand_id";

    public static final String STORE_NAME = "storeName";

    public static final String DB_STORE_NAME = "store_name";

    public static final String STORE_NICK = "storeNick";

    public static final String DB_STORE_NICK = "store_nick";

    public static final String PROVINCE = "province";

    public static final String DB_PROVINCE = "province";

    public static final String CITY = "city";

    public static final String DB_CITY = "city";

    public static final String DISTRICT = "district";

    public static final String DB_DISTRICT = "district";

    public static final String REGION = "region";

    public static final String DB_REGION = "region";

    public static final String ADDRESS = "address";

    public static final String DB_ADDRESS = "address";

    public static final String CONTACT = "contact";

    public static final String DB_CONTACT = "contact";

    public static final String CONTACT_TEL = "contactTel";

    public static final String DB_CONTACT_TEL = "contact_tel";

    public static final String CONTACT_JOB = "contactJob";

    public static final String DB_CONTACT_JOB = "contact_job";

    public static final String IT_CONTACT = "itContact";

    public static final String DB_IT_CONTACT = "it_contact";

    public static final String IT_CONTACT_TEL = "itContactTel";

    public static final String DB_IT_CONTACT_TEL = "it_contact_tel";

    public static final String SMS_SIGN = "smsSign";

    public static final String DB_SMS_SIGN = "sms_sign";

    public static final String INIT_FLAG = "initFlag";

    public static final String DB_INIT_FLAG = "init_flag";

    public static final String ENABLE_FLAG = "enableFlag";

    public static final String DB_ENABLE_FLAG = "enable_flag";

    public static final String DELETE_FLAG = "deleteFlag";

    public static final String DB_DELETE_FLAG = "delete_flag";

    public static final String CREATE_TIME = "createTime";

    public static final String DB_CREATE_TIME = "create_time";

    public static final String CREATE_USER = "createUser";

    public static final String DB_CREATE_USER = "create_user";

    public static final String UPDATE_TIME = "updateTime";

    public static final String DB_UPDATE_TIME = "update_time";

    public static final String UPDATE_USER = "updateUser";

    public static final String DB_UPDATE_USER = "update_user";
}