package pro.chenggang.project.reactive.mybatis.support.common.mapper;

import org.apache.ibatis.annotations.Mapper;
import pro.chenggang.project.reactive.mybatis.support.common.mapper.dynamic.ProjectDynamicMapper;

/**
 * auto generated mapper
 *
 * @author autoGenerated
 */
@Mapper
public interface ProjectMapper extends ProjectDynamicMapper {

}